### ISSUE TITLE
请问你这个工具里SM2的曲线是国密推荐的曲线吗？

### ISSUE THREAD

**Issue by ZZMarquis** [zweib730/SM9-misc#3]
请问你这个工具里SM2的曲线是国密推荐的曲线吗？

**Comment by zweib730** [comment]
是的。




| |
zweib
邮箱：zweib729@163.com
|

Signature is customized by Netease Mail Master

在2018年07月29日 20:44，ZZMarquis 写道：

请问你这个工具里SM2的曲线是国密推荐的曲线吗？

**Comment by ZZMarquis** [comment]
曲线参数：
p=FFFFFFFE FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF 00000000 FFFFFFFF FFFFFFFF
a=FFFFFFFE FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF 00000000 FFFFFFFF FFFFFFFC
b=28E9FA9E 9D9F5E34 4D5A9E4B CF6509A7 F39789F5 15AB8F92 DDBCBD41 4D940E93
n=FFFFFFFE FFFFFFFF FFFFFFFF FFFFFFFF 7203DF6B 21C6052B 53BBF409 39D54123
Gx=32C4AE2C 1F198119 5F990446 6A39C994 8FE30BBF F2660BE1 715A4589 334C74C7
Gy=BC3736A2 F4F6779C 59BDCEE3 6B692153 D0A9877C C62A4740 02DF32E5 2139F0A0

是上面这些不？

**Comment by zweib730** [comment]
是这条曲线，我的库已经用了很长时间了，跟其他厂家硬件加密卡通信的，应该不会那么容易出错。




| |
zweib
邮箱：zweib729@163.com
|

Signature is customized by Netease Mail Master

在2018年07月30日 17:31，ZZMarquis 写道：

曲线参数：
p=FFFFFFFE FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF 00000000 FFFFFFFF FFFFFFFF
a=FFFFFFFE FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF 00000000 FFFFFFFF FFFFFFFC
b=28E9FA9E 9D9F5E34 4D5A9E4B CF6509A7 F39789F5 15AB8F92 DDBCBD41 4D940E93
n=FFFFFFFE FFFFFFFF FFFFFFFF FFFFFFFF 7203DF6B 21C6052B 53BBF409 39D54123
Gx=32C4AE2C 1F198119 5F990446 6A39C994 8FE30BBF F2660BE1 715A4589 334C74C7
Gy=BC3736A2 F4F6779C 59BDCEE3 6B692153 D0A9877C C62A4740 02DF32E5 2139F0A0

是上面这些不？

**Comment by ZZMarquis** [comment]
@zweib730 好的，谢谢
