### ISSUE TITLE
请问你是基于GMSSL源码做的嘛？

### ISSUE THREAD

**Issue by guchuanlu** [zweib730/SM9-misc#4]

**Comment by zweib730** [comment]
不是，自研实现。




| |
zweib
邮箱：zweib729@163.com
|

Signature is customized by Netease Mail Master

在2018年11月22日 13:38，guchuanlu 写道：

**Comment by guchuanlu** [comment]
感谢您的回复，最近正在研究SM9加解密方面的事情，您方便将加解密方便的源码分享一下吗?万分感谢

**Comment by guchuanlu** [comment]
你好，当主私钥一致时，去生成主公钥以及用户私钥，发现主公钥生成一致，用户私钥每次生成都是随机值，按照您的经验来看，可能是哪边的问题，我这边在csdn上下载的代码，应该就是您的自研的那个代码，还请指点一下。。。
